export const toDoConstant = {
    GET_ALL_REQUEST : "GET_ALL_REQUEST_TODO",
    GET_ALL_SUCCESS : "GET_ALL_SUCCESS_TODO",
    GET_ALL_FAIL : "GET_ALL_FAIL_TODO",
    ADD_REQUEST: "ADD_REQUEST_TODO",
    ADD_SUCCESS: "ADD_SUCCESS_TODO",
    ADD_FAIL: "ADD_FAIL_TODO",
    UPDATE: "UPDATE_TODO",
    REMOVE: "REMOVE_TODO",
    SET_BUTTON_TEXT: "SET_BUTTON_TEXT_TODO",
    SELECT: "SELECT_TODO",
}

export default toDoConstant;